ignore:
  - "node_modules"
  - "dist"
  - "**/*.test.ts"
  - "**/*.spec.ts"
  - ".git"
  - ".next"
  - ".astro"

rules:
  # Architecture
  - doc: "docs/src/content/docs/architecture/overview.md"
    source: 
      - "ARCHITECTURE.md"

  - doc: "docs/src/content/docs/architecture/coding-standards.md"
    source:
      - "CODE.md"

  # UI System
  - doc: "docs/src/content/docs/ui/theming.md"
    source:
      - "THEME.md"
      - "src/styles.css"
    
  # Module Development
  - doc: "docs/src/content/docs/module-dev/introduction.md"
    source:
      - "MODULES.md"
