// GENERATED CODE - DO NOT MODIFY
import { defineApi } from '@/lib/api/api-docs';
import { ApiGuard } from '@/lib/api/api-guard';
import { parseQuery } from '@/lib/api/api-query';
import { HookSystem } from '@/lib/modules/hooks';
import { z } from 'zod';
import { JobService } from '@modules/orchestrator-api/src/services/job-service';
import { JobStatus } from '@modules/orchestrator-api/src/sdk';

// GENERATED CODE - DO NOT MODIFY
export const GET = defineApi(
  async (context) => {
    const filterOptions = {
      fields: {
        id: 'string',
        type: 'string',
        userId: 'string',
        actorId: 'string',
        actorType: 'string',
        status: 'enum',
        progress: 'number',
        lockedBy: 'string',
        lockedAt: 'date',
        startedAt: 'date',
        completedAt: 'date',
        createdAt: 'date',
        updatedAt: 'date',
        retryCount: 'number',
        maxRetries: 'number',
        nextRetryAt: 'date',
      },
      searchFields: ['id', 'type', 'userId', 'actorId', 'actorType', 'lockedBy'],
    } as const;

    const { where, take, skip, orderBy } = parseQuery(
      new URL(context.request.url).searchParams,
      filterOptions,
    );

    // Security Check
    // Pass query params as input to role check
    await ApiGuard.protect(context, 'job-owner', { ...context.params, where, take, skip, orderBy });

    const select = {
      id: true,
      type: true,
      userId: true,
      actorId: true,
      actorType: true,
      payload: true,
      result: true,
      error: true,
      status: true,
      progress: true,
      lockedBy: true,
      lockedAt: true,
      startedAt: true,
      completedAt: true,
      createdAt: true,
      updatedAt: true,
      retryCount: true,
      maxRetries: true,
      nextRetryAt: true,
      logs: { take: 10 },
    };

    const actor = context.locals.actor;
    const result = await JobService.list({ where, take, skip, orderBy, select }, actor);

    if (!result.success) {
      return new Response(JSON.stringify({ error: result.error }), { status: 500 });
    }

    const data = result.data || [];
    const total = result.total || 0;

    // Analytics Hook
    await HookSystem.dispatch('job.list.viewed', {
      count: data.length,
      actorId: actor?.id || 'anonymous',
    });

    return { success: true, data, meta: { total } };
  },
  {
    summary: 'List Jobs',
    tags: ['Job'],
    parameters: [
      { name: 'take', in: 'query', schema: { type: 'integer' } },
      { name: 'skip', in: 'query', schema: { type: 'integer' } },
      { name: 'search', in: 'query', schema: { type: 'string' } },
      {
        name: 'orderBy',
        in: 'query',
        schema: { type: 'string' },
        description: 'Ordering (format: field:asc or field:desc)',
      },
      {
        name: 'id.eq',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by id (eq)',
      },
      {
        name: 'id.ne',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by id (ne)',
      },
      {
        name: 'id.contains',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by id (contains)',
      },
      {
        name: 'id.startsWith',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by id (startsWith)',
      },
      {
        name: 'id.endsWith',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by id (endsWith)',
      },
      {
        name: 'id.in',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by id (in)',
      },
      {
        name: 'id',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by id (eq)',
      },
      {
        name: 'type.eq',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by type (eq)',
      },
      {
        name: 'type.ne',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by type (ne)',
      },
      {
        name: 'type.contains',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by type (contains)',
      },
      {
        name: 'type.startsWith',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by type (startsWith)',
      },
      {
        name: 'type.endsWith',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by type (endsWith)',
      },
      {
        name: 'type.in',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by type (in)',
      },
      {
        name: 'type',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by type (eq)',
      },
      {
        name: 'userId.eq',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by userId (eq)',
      },
      {
        name: 'userId.ne',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by userId (ne)',
      },
      {
        name: 'userId.contains',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by userId (contains)',
      },
      {
        name: 'userId.startsWith',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by userId (startsWith)',
      },
      {
        name: 'userId.endsWith',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by userId (endsWith)',
      },
      {
        name: 'userId.in',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by userId (in)',
      },
      {
        name: 'userId',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by userId (eq)',
      },
      {
        name: 'actorId.eq',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by actorId (eq)',
      },
      {
        name: 'actorId.ne',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by actorId (ne)',
      },
      {
        name: 'actorId.contains',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by actorId (contains)',
      },
      {
        name: 'actorId.startsWith',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by actorId (startsWith)',
      },
      {
        name: 'actorId.endsWith',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by actorId (endsWith)',
      },
      {
        name: 'actorId.in',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by actorId (in)',
      },
      {
        name: 'actorId',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by actorId (eq)',
      },
      {
        name: 'actorType.eq',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by actorType (eq)',
      },
      {
        name: 'actorType.ne',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by actorType (ne)',
      },
      {
        name: 'actorType.contains',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by actorType (contains)',
      },
      {
        name: 'actorType.startsWith',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by actorType (startsWith)',
      },
      {
        name: 'actorType.endsWith',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by actorType (endsWith)',
      },
      {
        name: 'actorType.in',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by actorType (in)',
      },
      {
        name: 'actorType',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by actorType (eq)',
      },
      {
        name: 'payload.eq',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by payload (eq)',
      },
      {
        name: 'payload.ne',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by payload (ne)',
      },
      {
        name: 'payload.in',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by payload (in)',
      },
      {
        name: 'payload',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by payload (eq)',
      },
      {
        name: 'result.eq',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by result (eq)',
      },
      {
        name: 'result.ne',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by result (ne)',
      },
      {
        name: 'result.in',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by result (in)',
      },
      {
        name: 'result',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by result (eq)',
      },
      {
        name: 'error.eq',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by error (eq)',
      },
      {
        name: 'error.ne',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by error (ne)',
      },
      {
        name: 'error.in',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by error (in)',
      },
      {
        name: 'error',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by error (eq)',
      },
      {
        name: 'status.eq',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by status (eq)',
      },
      {
        name: 'status.ne',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by status (ne)',
      },
      {
        name: 'status.in',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by status (in)',
      },
      {
        name: 'status',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by status (eq)',
      },
      {
        name: 'progress.eq',
        in: 'query',
        schema: { type: 'number' },
        required: false,
        description: 'Filter by progress (eq)',
      },
      {
        name: 'progress.ne',
        in: 'query',
        schema: { type: 'number' },
        required: false,
        description: 'Filter by progress (ne)',
      },
      {
        name: 'progress.gt',
        in: 'query',
        schema: { type: 'number' },
        required: false,
        description: 'Filter by progress (gt)',
      },
      {
        name: 'progress.gte',
        in: 'query',
        schema: { type: 'number' },
        required: false,
        description: 'Filter by progress (gte)',
      },
      {
        name: 'progress.lt',
        in: 'query',
        schema: { type: 'number' },
        required: false,
        description: 'Filter by progress (lt)',
      },
      {
        name: 'progress.lte',
        in: 'query',
        schema: { type: 'number' },
        required: false,
        description: 'Filter by progress (lte)',
      },
      {
        name: 'progress.in',
        in: 'query',
        schema: { type: 'number' },
        required: false,
        description: 'Filter by progress (in)',
      },
      {
        name: 'progress',
        in: 'query',
        schema: { type: 'number' },
        required: false,
        description: 'Filter by progress (eq)',
      },
      {
        name: 'lockedBy.eq',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by lockedBy (eq)',
      },
      {
        name: 'lockedBy.ne',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by lockedBy (ne)',
      },
      {
        name: 'lockedBy.contains',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by lockedBy (contains)',
      },
      {
        name: 'lockedBy.startsWith',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by lockedBy (startsWith)',
      },
      {
        name: 'lockedBy.endsWith',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by lockedBy (endsWith)',
      },
      {
        name: 'lockedBy.in',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by lockedBy (in)',
      },
      {
        name: 'lockedBy',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by lockedBy (eq)',
      },
      {
        name: 'lockedAt.eq',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by lockedAt (eq)',
      },
      {
        name: 'lockedAt.ne',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by lockedAt (ne)',
      },
      {
        name: 'lockedAt.gt',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by lockedAt (gt)',
      },
      {
        name: 'lockedAt.gte',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by lockedAt (gte)',
      },
      {
        name: 'lockedAt.lt',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by lockedAt (lt)',
      },
      {
        name: 'lockedAt.lte',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by lockedAt (lte)',
      },
      {
        name: 'lockedAt.in',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by lockedAt (in)',
      },
      {
        name: 'lockedAt',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by lockedAt (eq)',
      },
      {
        name: 'startedAt.eq',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by startedAt (eq)',
      },
      {
        name: 'startedAt.ne',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by startedAt (ne)',
      },
      {
        name: 'startedAt.gt',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by startedAt (gt)',
      },
      {
        name: 'startedAt.gte',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by startedAt (gte)',
      },
      {
        name: 'startedAt.lt',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by startedAt (lt)',
      },
      {
        name: 'startedAt.lte',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by startedAt (lte)',
      },
      {
        name: 'startedAt.in',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by startedAt (in)',
      },
      {
        name: 'startedAt',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by startedAt (eq)',
      },
      {
        name: 'completedAt.eq',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by completedAt (eq)',
      },
      {
        name: 'completedAt.ne',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by completedAt (ne)',
      },
      {
        name: 'completedAt.gt',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by completedAt (gt)',
      },
      {
        name: 'completedAt.gte',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by completedAt (gte)',
      },
      {
        name: 'completedAt.lt',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by completedAt (lt)',
      },
      {
        name: 'completedAt.lte',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by completedAt (lte)',
      },
      {
        name: 'completedAt.in',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by completedAt (in)',
      },
      {
        name: 'completedAt',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by completedAt (eq)',
      },
      {
        name: 'createdAt.eq',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by createdAt (eq)',
      },
      {
        name: 'createdAt.ne',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by createdAt (ne)',
      },
      {
        name: 'createdAt.gt',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by createdAt (gt)',
      },
      {
        name: 'createdAt.gte',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by createdAt (gte)',
      },
      {
        name: 'createdAt.lt',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by createdAt (lt)',
      },
      {
        name: 'createdAt.lte',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by createdAt (lte)',
      },
      {
        name: 'createdAt.in',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by createdAt (in)',
      },
      {
        name: 'createdAt',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by createdAt (eq)',
      },
      {
        name: 'updatedAt.eq',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by updatedAt (eq)',
      },
      {
        name: 'updatedAt.ne',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by updatedAt (ne)',
      },
      {
        name: 'updatedAt.gt',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by updatedAt (gt)',
      },
      {
        name: 'updatedAt.gte',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by updatedAt (gte)',
      },
      {
        name: 'updatedAt.lt',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by updatedAt (lt)',
      },
      {
        name: 'updatedAt.lte',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by updatedAt (lte)',
      },
      {
        name: 'updatedAt.in',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by updatedAt (in)',
      },
      {
        name: 'updatedAt',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by updatedAt (eq)',
      },
      {
        name: 'retryCount.eq',
        in: 'query',
        schema: { type: 'number' },
        required: false,
        description: 'Filter by retryCount (eq)',
      },
      {
        name: 'retryCount.ne',
        in: 'query',
        schema: { type: 'number' },
        required: false,
        description: 'Filter by retryCount (ne)',
      },
      {
        name: 'retryCount.gt',
        in: 'query',
        schema: { type: 'number' },
        required: false,
        description: 'Filter by retryCount (gt)',
      },
      {
        name: 'retryCount.gte',
        in: 'query',
        schema: { type: 'number' },
        required: false,
        description: 'Filter by retryCount (gte)',
      },
      {
        name: 'retryCount.lt',
        in: 'query',
        schema: { type: 'number' },
        required: false,
        description: 'Filter by retryCount (lt)',
      },
      {
        name: 'retryCount.lte',
        in: 'query',
        schema: { type: 'number' },
        required: false,
        description: 'Filter by retryCount (lte)',
      },
      {
        name: 'retryCount.in',
        in: 'query',
        schema: { type: 'number' },
        required: false,
        description: 'Filter by retryCount (in)',
      },
      {
        name: 'retryCount',
        in: 'query',
        schema: { type: 'number' },
        required: false,
        description: 'Filter by retryCount (eq)',
      },
      {
        name: 'maxRetries.eq',
        in: 'query',
        schema: { type: 'number' },
        required: false,
        description: 'Filter by maxRetries (eq)',
      },
      {
        name: 'maxRetries.ne',
        in: 'query',
        schema: { type: 'number' },
        required: false,
        description: 'Filter by maxRetries (ne)',
      },
      {
        name: 'maxRetries.gt',
        in: 'query',
        schema: { type: 'number' },
        required: false,
        description: 'Filter by maxRetries (gt)',
      },
      {
        name: 'maxRetries.gte',
        in: 'query',
        schema: { type: 'number' },
        required: false,
        description: 'Filter by maxRetries (gte)',
      },
      {
        name: 'maxRetries.lt',
        in: 'query',
        schema: { type: 'number' },
        required: false,
        description: 'Filter by maxRetries (lt)',
      },
      {
        name: 'maxRetries.lte',
        in: 'query',
        schema: { type: 'number' },
        required: false,
        description: 'Filter by maxRetries (lte)',
      },
      {
        name: 'maxRetries.in',
        in: 'query',
        schema: { type: 'number' },
        required: false,
        description: 'Filter by maxRetries (in)',
      },
      {
        name: 'maxRetries',
        in: 'query',
        schema: { type: 'number' },
        required: false,
        description: 'Filter by maxRetries (eq)',
      },
      {
        name: 'nextRetryAt.eq',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by nextRetryAt (eq)',
      },
      {
        name: 'nextRetryAt.ne',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by nextRetryAt (ne)',
      },
      {
        name: 'nextRetryAt.gt',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by nextRetryAt (gt)',
      },
      {
        name: 'nextRetryAt.gte',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by nextRetryAt (gte)',
      },
      {
        name: 'nextRetryAt.lt',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by nextRetryAt (lt)',
      },
      {
        name: 'nextRetryAt.lte',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by nextRetryAt (lte)',
      },
      {
        name: 'nextRetryAt.in',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by nextRetryAt (in)',
      },
      {
        name: 'nextRetryAt',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by nextRetryAt (eq)',
      },
      {
        name: 'logs.eq',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by logs (eq)',
      },
      {
        name: 'logs.ne',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by logs (ne)',
      },
      {
        name: 'logs.in',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by logs (in)',
      },
      {
        name: 'logs',
        in: 'query',
        schema: { type: 'string' },
        required: false,
        description: 'Filter by logs (eq)',
      },
    ],
    responses: {
      200: {
        description: 'OK',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                data: {
                  type: 'array',
                  items: {
                    type: 'object',
                    properties: {
                      id: { type: 'string' },
                      type: { type: 'string' },
                      userId: { type: 'string' },
                      actorId: { type: 'string' },
                      actorType: { type: 'string' },
                      payload: { type: 'object' },
                      result: { type: 'object' },
                      error: { type: 'object' },
                      status: { type: 'string' },
                      progress: { type: 'number' },
                      lockedBy: { type: 'string' },
                      lockedAt: { type: 'string', format: 'date-time' },
                      startedAt: { type: 'string', format: 'date-time' },
                      completedAt: { type: 'string', format: 'date-time' },
                      createdAt: { type: 'string', format: 'date-time' },
                      updatedAt: { type: 'string', format: 'date-time' },
                      retryCount: { type: 'number' },
                      maxRetries: { type: 'number' },
                      nextRetryAt: { type: 'string', format: 'date-time' },
                      logs: { type: 'array', items: { type: 'string' } },
                    },
                    required: ['type', 'updatedAt', 'logs'],
                  },
                },
                meta: {
                  type: 'object',
                  properties: {
                    total: { type: 'integer' },
                  },
                },
              },
            },
          },
        },
      },
    },
  },
);
export const POST = defineApi(
  async (context) => {
    const body = await context.request.json();

    // Security Check
    await ApiGuard.protect(context, 'job-owner', { ...context.params, ...body });

    // Zod Validation
    const schema = z.object({
      type: z.string(),
      userId: z.string().optional(),
      actorId: z.string().optional(),
      actorType: z.string().optional(),
      payload: z.unknown().optional(),
      result: z.unknown().optional(),
      error: z.unknown().optional(),
      status: z.nativeEnum(JobStatus).optional(),
      progress: z.number().int().optional(),
      lockedBy: z.string().optional(),
      lockedAt: z.string().datetime().optional(),
      startedAt: z.string().datetime().optional(),
      completedAt: z.string().datetime().optional(),
      retryCount: z.number().int().optional(),
      maxRetries: z.number().int().optional(),
      nextRetryAt: z.string().datetime().optional(),
    });

    const validated = schema.parse(body);
    const select = {
      id: true,
      type: true,
      userId: true,
      actorId: true,
      actorType: true,
      payload: true,
      result: true,
      error: true,
      status: true,
      progress: true,
      lockedBy: true,
      lockedAt: true,
      startedAt: true,
      completedAt: true,
      createdAt: true,
      updatedAt: true,
      retryCount: true,
      maxRetries: true,
      nextRetryAt: true,
      logs: { take: 10 },
    };
    const actor = context.locals.actor;

    const result = await JobService.create(validated, select, actor);

    if (!result.success) {
      return new Response(JSON.stringify({ error: result.error }), { status: 400 });
    }

    return new Response(JSON.stringify({ success: true, data: result.data }), { status: 201 });
  },
  {
    summary: 'Create Job',
    tags: ['Job'],
    requestBody: {
      content: {
        'application/json': {
          schema: {
            type: 'object',
            properties: {
              id: { type: 'string' },
              type: { type: 'string' },
              userId: { type: 'string' },
              actorId: { type: 'string' },
              actorType: { type: 'string' },
              payload: { type: 'object' },
              result: { type: 'object' },
              error: { type: 'object' },
              status: { type: 'string' },
              progress: { type: 'number' },
              lockedBy: { type: 'string' },
              lockedAt: { type: 'string', format: 'date-time' },
              startedAt: { type: 'string', format: 'date-time' },
              completedAt: { type: 'string', format: 'date-time' },
              createdAt: { type: 'string', format: 'date-time' },
              updatedAt: { type: 'string', format: 'date-time' },
              retryCount: { type: 'number' },
              maxRetries: { type: 'number' },
              nextRetryAt: { type: 'string', format: 'date-time' },
              logs: { type: 'array', items: { type: 'string' } },
            },
            required: ['type', 'updatedAt', 'logs'],
          },
        },
      },
    },
    responses: {
      200: {
        description: 'OK',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                data: {
                  type: 'object',
                  properties: {
                    id: { type: 'string' },
                    type: { type: 'string' },
                    userId: { type: 'string' },
                    actorId: { type: 'string' },
                    actorType: { type: 'string' },
                    payload: { type: 'object' },
                    result: { type: 'object' },
                    error: { type: 'object' },
                    status: { type: 'string' },
                    progress: { type: 'number' },
                    lockedBy: { type: 'string' },
                    lockedAt: { type: 'string', format: 'date-time' },
                    startedAt: { type: 'string', format: 'date-time' },
                    completedAt: { type: 'string', format: 'date-time' },
                    createdAt: { type: 'string', format: 'date-time' },
                    updatedAt: { type: 'string', format: 'date-time' },
                    retryCount: { type: 'number' },
                    maxRetries: { type: 'number' },
                    nextRetryAt: { type: 'string', format: 'date-time' },
                    logs: { type: 'array', items: { type: 'string' } },
                  },
                  required: ['type', 'updatedAt', 'logs'],
                },
              },
            },
          },
        },
      },
    },
  },
);
