// GENERATED CODE - DO NOT MODIFY
// This file was generated by the AgentBuilder.
import { JobProcessor, ProcessorConfig, AgentJob } from '@nexical/agent/src/core/processor.js';
import type { AgentContext, AgentResult } from '@nexical/agent/src/core/types.js';
import { z } from 'zod';

export class EchoProcessor extends JobProcessor<{ message: string }> {
  static jobType: string = 'EchoProcessor';

  schema = z.object({
    message: z.string(),
  });

  constructor(config: ProcessorConfig) {
    super(config);
  }

  public async process(
    job: AgentJob<{ message: string }>,
    context: AgentContext,
  ): Promise<AgentResult> {
    const { message } = job.payload;
    context.logger.info(`[EchoProcessor] Processing job ${job.id} with message: ${message}`);

    // Echo the message back as the result
    return {
      success: true,
      data: { echo: message, processedAt: new Date().toISOString() },
    };
  }
}
