import { useEffect } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { useCreateUser, useUpdateUser } from '@/hooks/use-user';
import { Permission } from '@modules/user-api/permissions';
import { useAuth } from '@/hooks/use-auth';
import { PasswordInput } from '@/components/ui/password-input';

// GENERATED CODE - DO NOT MODIFY
// This file was generated by the FormBuilder.
export function UserForm({
  id,
  initialData,
  onSuccess,
}: {
  id?: string;
  initialData?: any;
  onSuccess?: () => void;
}) {
  const isEdit = !!id,
    createMutation = useCreateUser(),
    updateMutation = useUpdateUser();
  const { user } = useAuth();
  const canCreate = Permission.check('user:create', user?.role || 'ANONYMOUS'),
    canUpdate = Permission.check('user:update', user?.role || 'ANONYMOUS');
  const schema = z.object({
    username: z.string().optional(),
    email: z.string().optional().email(),
    passwordUpdatedAt: z.string().datetime().optional(),
    emailVerified: z.string().datetime().optional(),
    name: z.string().optional(),
    image: z.string().optional(),
    role: z.nativeEnum(SiteRole).optional(),
    status: z.nativeEnum(UserStatus).optional(),
  });
  type FormData = z.infer<typeof schema>;
  const {
    register,
    handleSubmit,
    reset,
    control,
    formState: { errors, isSubmitting },
  } = useForm<FormData>({
    resolver: zodResolver(schema),
    defaultValues: initialData || {},
  });
  useEffect(() => {
    if (initialData) {
      reset(initialData);
    }
  }, [initialData, reset]);
  const onSubmit = (data: FormData) => {
    if (isEdit && id) {
      updateMutation.mutate({ id, data }, { onSuccess });
    } else {
      createMutation.mutate(data, { onSuccess });
    }
  };
  return (
    <form onSubmit="{handleSubmit(onSubmit)}" className="space-y-4">
      <div>
        <label htmlFor="username" className="block text-sm font-medium text-gray-700">
          Username
        </label>
        <div className="mt-1">
          <input
            type="text"
            id="username"
            {...register('username')}
            className="shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md"
          />
        </div>
        {errors.username && (
          <p className="mt-2 text-sm text-red-600">{errors.username?.message as string}</p>
        )}
      </div>
      <div>
        <label htmlFor="email" className="block text-sm font-medium text-gray-700">
          Email
        </label>
        <div className="mt-1">
          <input
            type="text"
            id="email"
            {...register('email')}
            className="shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md"
          />
        </div>
        {errors.email && (
          <p className="mt-2 text-sm text-red-600">{errors.email?.message as string}</p>
        )}
      </div>
      <div>
        <label htmlFor="password" className="block text-sm font-medium text-gray-700">
          Password
        </label>
        <div className="mt-1">
          <PasswordInput
            id="password"
            error={errors.password?.message as string}
            {...register('password')}
          />
        </div>
      </div>
      <div>
        <label htmlFor="passwordUpdatedAt" className="block text-sm font-medium text-gray-700">
          Password Updated At
        </label>
        <div className="mt-1">
          <input
            type="datetime-local"
            id="passwordUpdatedAt"
            {...register('passwordUpdatedAt')}
            className="shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md"
          />
        </div>
        {errors.passwordUpdatedAt && (
          <p className="mt-2 text-sm text-red-600">{errors.passwordUpdatedAt?.message as string}</p>
        )}
      </div>
      <div>
        <label htmlFor="emailVerified" className="block text-sm font-medium text-gray-700">
          Email Verified
        </label>
        <div className="mt-1">
          <input
            type="datetime-local"
            id="emailVerified"
            {...register('emailVerified')}
            className="shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md"
          />
        </div>
        {errors.emailVerified && (
          <p className="mt-2 text-sm text-red-600">{errors.emailVerified?.message as string}</p>
        )}
      </div>
      <div>
        <label htmlFor="name" className="block text-sm font-medium text-gray-700">
          Name
        </label>
        <div className="mt-1">
          <input
            type="text"
            id="name"
            {...register('name')}
            className="shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md"
          />
        </div>
        {errors.name && (
          <p className="mt-2 text-sm text-red-600">{errors.name?.message as string}</p>
        )}
      </div>
      <div>
        <label htmlFor="image" className="block text-sm font-medium text-gray-700">
          Image
        </label>
        <div className="mt-1">
          <input
            type="text"
            id="image"
            {...register('image')}
            className="shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md"
          />
        </div>
        {errors.image && (
          <p className="mt-2 text-sm text-red-600">{errors.image?.message as string}</p>
        )}
      </div>
      <div>
        <label htmlFor="role" className="block text-sm font-medium text-gray-700">
          Role
        </label>
        <div className="mt-1">
          <input
            type="text"
            id="role"
            {...register('role')}
            className="shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md"
          />
        </div>
        {errors.role && (
          <p className="mt-2 text-sm text-red-600">{errors.role?.message as string}</p>
        )}
      </div>
      <div>
        <label htmlFor="status" className="block text-sm font-medium text-gray-700">
          Status
        </label>
        <div className="mt-1">
          <input
            type="text"
            id="status"
            {...register('status')}
            className="shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md"
          />
        </div>
        {errors.status && (
          <p className="mt-2 text-sm text-red-600">{errors.status?.message as string}</p>
        )}
      </div>
      {(isEdit ? canUpdate : canCreate) && (
        <button
          type="submit"
          disabled="{isSubmitting}"
          className="inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 disabled:opacity-50"
        >
          {isSubmitting ? 'Saving...' : isEdit ? 'Update' : 'Create'}
        </button>
      )}
    </form>
  );
}
