import { useState } from 'react';
import { useUserQuery, useDeleteUser } from '@/hooks/use-user';
import { Permission } from '@modules/user-api/permissions';
import { useAuth } from '@/hooks/use-auth';
import { type ColumnDef } from '@tanstack/react-table';
import { DataTable } from '@/components/ui/data-table/data-table';
import { DataTableColumnHeader } from '@/components/ui/data-table/data-table-column-header';
import { Button } from '@/components/ui/button';
import { MoreHorizontal, Trash, Pencil } from 'lucide-react';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import { type User } from '@modules/user-api/src/sdk';
import { ConfirmFormDeletion } from '@/components/ui/confirm-form-deletion';
import { UserForm } from './UserForm';
import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTitle,
  SheetDescription,
} from '@/components/ui/sheet';

// GENERATED CODE - DO NOT MODIFY
// This file was generated by the TableBuilder.
export function UserTable() {
  const { data, isLoading } = useUserQuery();
  const deleteMutation = useDeleteUser();
  const { user } = useAuth();
  const canDelete = Permission.check('user:delete', user?.role || 'ANONYMOUS'),
    canUpdate = Permission.check('user:update', user?.role || 'ANONYMOUS');
  const [editingItem, setEditingItem] = useState<User | null>(null);
  const [deletingItem, setDeletingItem] = useState<User | null>(null);
  if (isLoading) {
    return <div>Loading...</div>;
  }
  const columns: ColumnDef<User>[] = [
    {
      accessorKey: 'id',
      header: ({ column }) => <DataTableColumnHeader column={column} title="Id" />,
      cell: ({ row }) => <div>{String(row.getValue('id') || '')}</div>,
    },
    {
      accessorKey: 'username',
      header: ({ column }) => <DataTableColumnHeader column={column} title="Username" />,
      cell: ({ row }) => <div>{String(row.getValue('username') || '')}</div>,
    },
    {
      accessorKey: 'email',
      header: ({ column }) => <DataTableColumnHeader column={column} title="Email" />,
      cell: ({ row }) => <div>{String(row.getValue('email') || '')}</div>,
    },
    {
      accessorKey: 'passwordUpdatedAt',
      header: ({ column }) => <DataTableColumnHeader column={column} title="PasswordUpdatedAt" />,
      cell: ({ row }) => <div>{String(row.getValue('passwordUpdatedAt') || '')}</div>,
    },
    {
      accessorKey: 'emailVerified',
      header: ({ column }) => <DataTableColumnHeader column={column} title="EmailVerified" />,
      cell: ({ row }) => <div>{String(row.getValue('emailVerified') || '')}</div>,
    },
    {
      accessorKey: 'name',
      header: ({ column }) => <DataTableColumnHeader column={column} title="Name" />,
      cell: ({ row }) => <div>{String(row.getValue('name') || '')}</div>,
    },
    {
      accessorKey: 'image',
      header: ({ column }) => <DataTableColumnHeader column={column} title="Image" />,
      cell: ({ row }) => <div>{String(row.getValue('image') || '')}</div>,
    },
    {
      accessorKey: 'role',
      header: ({ column }) => <DataTableColumnHeader column={column} title="Role" />,
      cell: ({ row }) => <div>{String(row.getValue('role') || '')}</div>,
    },
    {
      accessorKey: 'status',
      header: ({ column }) => <DataTableColumnHeader column={column} title="Status" />,
      cell: ({ row }) => <div>{String(row.getValue('status') || '')}</div>,
    },
    {
      accessorKey: 'createdAt',
      header: ({ column }) => <DataTableColumnHeader column={column} title="CreatedAt" />,
      cell: ({ row }) => <div>{String(row.getValue('createdAt') || '')}</div>,
    },
    {
      accessorKey: 'updatedAt',
      header: ({ column }) => <DataTableColumnHeader column={column} title="UpdatedAt" />,
      cell: ({ row }) => <div>{String(row.getValue('updatedAt') || '')}</div>,
    },
    {
      id: 'actions',
      cell: ({ row }) => {
        const item = row.original;
        return (
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button variant="ghost" className="h-8 w-8 p-0">
                <span className="sr-only">Open menu</span>
                <MoreHorizontal className="h-4 w-4" />
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end">
              <DropdownMenuLabel>Actions</DropdownMenuLabel>
              <DropdownMenuSeparator />
              {canUpdate && (
                <DropdownMenuItem onClick={() => setEditingItem(item)}>
                  <Pencil className="mr-2 h-4 w-4" />
                  Edit
                </DropdownMenuItem>
              )}
              {canDelete && (
                <DropdownMenuItem
                  className="text-red-600 focus:text-red-600"
                  onClick={() => setDeletingItem(item)}
                >
                  <Trash className="mr-2 h-4 w-4" />
                  Delete
                </DropdownMenuItem>
              )}
            </DropdownMenuContent>
          </DropdownMenu>
        );
      },
    },
  ];
  return (
    <div className="space-y-4">
      <DataTable columns={columns} data={data || []} />
      {
        <Sheet open={!!editingItem} onOpenChange={(open) => !open && setEditingItem(null)}>
          <SheetContent>
            <SheetHeader>
              <SheetTitle>Edit User</SheetTitle>
              <SheetDescription>Make changes to the user.</SheetDescription>
            </SheetHeader>
            <div className="mt-4">
              {editingItem && (
                <UserForm
                  id={editingItem.id}
                  initialData={editingItem}
                  onSuccess={() => setEditingItem(null)}
                />
              )}
            </div>
          </SheetContent>
        </Sheet>
      }
      <ConfirmFormDeletion
        isOpen={!!deletingItem}
        onOpenChange={(open) => !open && setDeletingItem(null)}
        resourceName="'User'"
        resourceIdentifier={deletingItem?.id || ''}
        onConfirm={() => {
          if (deletingItem) deleteMutation.mutate(deletingItem.id);
          setDeletingItem(null);
        }}
      />
    </div>
  );
}
