import { useState } from 'react';
import { useTranslation } from 'react-i18next';
import { useUserQuery, useDeleteUser } from '@/hooks/use-user';
import { Permission } from '@modules/user-api/src/permissions';
import { useAuth } from '@/hooks/use-auth';
import { type ColumnDef } from '@tanstack/react-table';
import { DataTable } from '@/components/ui/data-table/data-table';
import { DataTableColumnHeader } from '@/components/ui/data-table/data-table-column-header';
import { Button } from '@/components/ui/button';
import { MoreHorizontal, Trash, Pencil } from 'lucide-react';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import { type User } from '@modules/user-api/src/sdk';
import { ConfirmFormDeletion } from '@/components/ui/confirm-form-deletion';
import { UserForm } from './UserForm';
import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTitle,
  SheetDescription,
} from '@/components/ui/sheet';

// GENERATED CODE - DO NOT MODIFY
// This file was generated by the TableBuilder.
export function UserTable() {
  const { t } = useTranslation();
  const { data, isLoading } = useUserQuery();
  const deleteMutation = useDeleteUser();
  const { user } = useAuth();
  const canDelete = Permission.check('user:delete', user?.role || 'ANONYMOUS'),
    canUpdate = Permission.check('user:update', user?.role || 'ANONYMOUS');
  const [editingItem, setEditingItem] = useState<User | null>(null);
  const [deletingItem, setDeletingItem] = useState<User | null>(null);
  if (isLoading) {
    return <div className="layout-centered py-12 text-subtle">{t('common.status.loading')}</div>;
  }
  const columns: ColumnDef<User>[] = [
    {
      accessorKey: 'id',
      header: ({ column }) => (
        <DataTableColumnHeader column={column} title={t('module.user.field.id')} />
      ),
      cell: ({ row }) => <div className="text-body-sm">{String(row.getValue('id') || '')}</div>,
    },
    {
      accessorKey: 'username',
      header: ({ column }) => (
        <DataTableColumnHeader column={column} title={t('module.user.field.username')} />
      ),
      cell: ({ row }) => (
        <div className="text-body-sm">{String(row.getValue('username') || '')}</div>
      ),
    },
    {
      accessorKey: 'email',
      header: ({ column }) => (
        <DataTableColumnHeader column={column} title={t('module.user.field.email')} />
      ),
      cell: ({ row }) => <div className="text-body-sm">{String(row.getValue('email') || '')}</div>,
    },
    {
      accessorKey: 'passwordUpdatedAt',
      header: ({ column }) => (
        <DataTableColumnHeader column={column} title={t('module.user.field.passwordUpdatedAt')} />
      ),
      cell: ({ row }) => (
        <div className="text-body-sm">{String(row.getValue('passwordUpdatedAt') || '')}</div>
      ),
    },
    {
      accessorKey: 'emailVerified',
      header: ({ column }) => (
        <DataTableColumnHeader column={column} title={t('module.user.field.emailVerified')} />
      ),
      cell: ({ row }) => (
        <div className="text-body-sm">{String(row.getValue('emailVerified') || '')}</div>
      ),
    },
    {
      accessorKey: 'name',
      header: ({ column }) => (
        <DataTableColumnHeader column={column} title={t('module.user.field.name')} />
      ),
      cell: ({ row }) => <div className="text-body-sm">{String(row.getValue('name') || '')}</div>,
    },
    {
      accessorKey: 'image',
      header: ({ column }) => (
        <DataTableColumnHeader column={column} title={t('module.user.field.image')} />
      ),
      cell: ({ row }) => <div className="text-body-sm">{String(row.getValue('image') || '')}</div>,
    },
    {
      accessorKey: 'role',
      header: ({ column }) => (
        <DataTableColumnHeader column={column} title={t('module.user.field.role')} />
      ),
      cell: ({ row }) => <div className="text-body-sm">{String(row.getValue('role') || '')}</div>,
    },
    {
      accessorKey: 'status',
      header: ({ column }) => (
        <DataTableColumnHeader column={column} title={t('module.user.field.status')} />
      ),
      cell: ({ row }) => <div className="text-body-sm">{String(row.getValue('status') || '')}</div>,
    },
    {
      accessorKey: 'createdAt',
      header: ({ column }) => (
        <DataTableColumnHeader column={column} title={t('module.user.field.createdAt')} />
      ),
      cell: ({ row }) => (
        <div className="text-body-sm">{String(row.getValue('createdAt') || '')}</div>
      ),
    },
    {
      accessorKey: 'updatedAt',
      header: ({ column }) => (
        <DataTableColumnHeader column={column} title={t('module.user.field.updatedAt')} />
      ),
      cell: ({ row }) => (
        <div className="text-body-sm">{String(row.getValue('updatedAt') || '')}</div>
      ),
    },
    {
      id: 'actions',
      cell: ({ row }) => {
        const item = row.original;
        return (
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button variant="ghost" className="btn-icon-sm btn-ghost">
                <span className="sr-only">Open menu</span>
                <MoreHorizontal className="icon-sm" />
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end" className="w-[160px]">
              <DropdownMenuLabel className="text-subtle-xs uppercase">
                {t('common.actions.label')}
              </DropdownMenuLabel>
              <DropdownMenuSeparator />
              {canUpdate && (
                <DropdownMenuItem
                  onClick={() => setEditingItem(item)}
                  className="gap-2 cursor-pointer"
                >
                  <Pencil className="icon-xs text-muted-foreground" />
                  {t('common.actions.edit')}
                </DropdownMenuItem>
              )}
              {canDelete && (
                <DropdownMenuItem
                  className="gap-2 text-destructive focus:text-destructive cursor-pointer"
                  onClick={() => setDeletingItem(item)}
                >
                  <Trash className="icon-xs" />
                  {t('common.actions.delete')}
                </DropdownMenuItem>
              )}
            </DropdownMenuContent>
          </DropdownMenu>
        );
      },
    },
  ];
  return (
    <div className="space-y-4 container-admin-table">
      <DataTable columns={columns} data={data || []} />
      {
        <Sheet open={!!editingItem} onOpenChange={(open) => !open && setEditingItem(null)}>
          <SheetContent className="w-dialog-lg sm:max-w-xl">
            <SheetHeader>
              <SheetTitle className="text-heading-md">{t('module.user.edit.title')}</SheetTitle>
              <SheetDescription className="text-subtle">
                {t('module.user.edit.description')}
              </SheetDescription>
            </SheetHeader>
            <div className="mt-8">
              {editingItem && (
                <UserForm
                  id={editingItem.id}
                  initialData={editingItem}
                  onSuccess={() => setEditingItem(null)}
                />
              )}
            </div>
          </SheetContent>
        </Sheet>
      }
      <ConfirmFormDeletion
        isOpen={!!deletingItem}
        onOpenChange={(open) => !open && setDeletingItem(null)}
        resourceName="'User'"
        resourceIdentifier={deletingItem?.id || ''}
        onConfirm={() => {
          if (deletingItem) deleteMutation.mutate(deletingItem.id);
          setDeletingItem(null);
        }}
      />
    </div>
  );
}
