// GENERATED CODE - DO NOT MODIFY BY HAND
// This file is automatically generated by the ArcNexus Generator.
// Any manual changes will be overwritten.
import { roleRegistry } from '@/lib/registries/role-registry';
import { Permissions } from '@/lib/security/permissions';

export async function init() {
  const roleModules = import.meta.glob('./roles/*.ts', { eager: true });
  for (const path in roleModules) {
    const mod = roleModules[path] as { [key: string]: unknown };
    const roleName = path.split('/').pop()?.replace('.ts', '');
    if (!roleName) continue;

    // Find the first exported class that looks like a RolePolicy (has check method)
    for (const key in mod) {
      const Exported = mod[key];
      if (typeof Exported === 'function' && Exported.prototype && Exported.prototype.check) {
        roleRegistry.register(roleName, new Exported());
        break;
      }
    }
  }
  const hookModules = import.meta.glob('./hooks/*.ts', { eager: true });
  for (const path in hookModules) {
    const mod = hookModules[path] as { init?: () => Promise<void> | void };
    if (typeof mod.init === 'function') {
      await mod.init();
    }
  }
  const emailInitModules = import.meta.glob('./emails/init.ts', { eager: true });
  for (const path in emailInitModules) {
    const mod = emailInitModules[path] as { initEmails?: () => Promise<void> | void };
    if (typeof mod.initEmails === 'function') {
      await mod.initEmails();
    }
  }
  const permissionModules = import.meta.glob('./permissions.ts', { eager: true });
  for (const path in permissionModules) {
    const mod = permissionModules[path] as { RolePermissions?: Record<string, string[]> };
    if (mod.RolePermissions) {
      for (const [role, actions] of Object.entries(mod.RolePermissions)) {
        Permissions.register(role, actions);
      }
    }
  }
}
