import { globby } from 'globby';
import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT_DIR = path.resolve(__dirname, '..');

async function generate() {
    const agentFiles = await globby('modules/*/src/agent/*.ts', { cwd: ROOT_DIR });

    const agents = await Promise.all(agentFiles.map(async file => {
        const parts = file.split('/');
        const moduleName = parts[1];
        const fileName = path.basename(file, '.ts');
        const key = `${moduleName}.${fileName}`;
        const importPath = `../../../${file.replace('.ts', '.js')}`;
        const variableName = `${moduleName}_${fileName}`.replace(/-/g, '_');

        const fileContent = await fs.readFile(path.join(ROOT_DIR, file), 'utf-8');
        const type = fileContent.includes('extends PersistentAgent') ? 'persistent' : 'job';

        return { key, variableName, importPath, type };
    }));

    const jobAgents = agents.filter(a => a.type === 'job');
    const persistentAgents = agents.filter(a => a.type === 'persistent');

    const imports = agents.map(a => `import { worker as ${a.variableName} } from '${a.importPath}';`).join('\n');
    const jobMapping = jobAgents.map(a => `  '${a.key}': ${a.variableName},`).join('\n');
    const persistentMapping = persistentAgents.map(a => `  '${a.key}': ${a.variableName},`).join('\n');

    const content = `// This file is auto-generated by scripts/generate-agent-registry.ts
import type { AgentWorker } from './core/types.js';

${imports}

export const jobProcessors: Record<string, any> = {
${jobMapping}
};

export const processors: Record<string, any> = {
${persistentMapping}
};
`;

    const outputPath = path.join(ROOT_DIR, 'packages/agent/src/registry.ts');

    // Ensure directory exists
    await fs.mkdir(path.dirname(outputPath), { recursive: true });

    await fs.writeFile(outputPath, content);
    console.log(`Generated Agent registry at ${outputPath}`);
}

generate().catch(console.error);
