import { globby } from 'globby';
import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT_DIR = path.resolve(__dirname, '..');

async function generate() {
  const sdkFiles = await globby('modules/*/src/sdk/index.ts', { cwd: ROOT_DIR });

  const modules = sdkFiles.map(file => {
    // file is like modules/user/src/sdk/index.ts
    const parts = file.split('/');
    const moduleName = parts[1]; // 'user'
    // Convert kebab-case or snake_case to PascalCase for the class name if needed,
    // but the instruction says convention is {PascalCaseName}SDK.
    // Assuming module 'user' -> UserSDK, 'team' -> TeamSDK.
    // If module name has dashes like 'api-key', it should probably be ApiKeySDK.
    const effectiveName = moduleName.endsWith('-api') ? moduleName.replace(/-api$/, '') : moduleName;
    const className = effectiveName
      .split(/[-_]/)
      .map(part => part.charAt(0).toUpperCase() + part.slice(1))
      .join('') + 'SDK';

    // relative path from packages/sdk/src/registry.generated.ts to modules/...
    // registry is in packages/sdk/src
    // module is in modules/user/src/sdk/index.ts
    // Use alias for robust resolution
    const importPath = `@modules/${moduleName}/src/sdk/index`;

    // Strip "-api" suffix from property name if present
    const propertyName = moduleName.endsWith('-api') ? moduleName.replace(/-api$/, '') : moduleName;

    return { name: propertyName, className, importPath };
  });

  const imports = modules.map(m => `import { ${m.className} } from '${m.importPath}';`).join('\n');
  const properties = modules.map(m => `  '${m.name}': ${m.className};`).join('\n');
  const initializers = modules.map(m => `    '${m.name}': new ${m.className}(client),`).join('\n');

  const content = `// This file is auto-generated by scripts/generate-sdk.ts
import { ApiClient } from '@nexical/sdk-core';
${imports}

export interface SdkRegistry {
${properties}
}

export function initializeSdkRegistry(client: ApiClient): SdkRegistry {
  return {
${initializers}
  };
}
`;

  const outputPath = path.join(ROOT_DIR, 'packages/sdk/src/registry.generated.ts');
  await fs.writeFile(outputPath, content);
  console.log(`Generated SDK registry at ${outputPath}`);
}

generate().catch(console.error);
