import { globby } from 'globby';
import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT_DIR = path.resolve(__dirname, '..');

async function generate() {
  const agentFiles = await globby('modules/*/src/agent/*.ts', { cwd: ROOT_DIR });

  const agents = await Promise.all(
    agentFiles.map(async (file) => {
      const parts = file.split('/');
      const moduleName = parts[1];
      const fileName = path.basename(file, '.ts');
      const key = `${moduleName}.${fileName}`;
      const importPath = `../../../${file.replace('.ts', '.js')}`;
      const variableName = `${moduleName}_${fileName}`.replace(/-/g, '_');

      const fileContent = await fs.readFile(path.join(ROOT_DIR, file), 'utf-8');
      const type = fileContent.includes('extends PersistentAgent') ? 'persistent' : 'job';

      return { key, variableName, importPath, type };
    }),
  );

  const jobAgents = agents.filter((a) => a.type === 'job');
  const persistentAgents = agents.filter((a) => a.type === 'persistent');

  // For job agents, import the class directly (not an instance)
  // For persistent agents, import the class directly too
  const imports = agents
    .map((a) => {
      const parts = a.key.split('.');
      const fileName = parts[1];
      const originalClassName = fileName
        .split('-')
        .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
        .join('');

      const prefixedClassName = a.variableName
        .split('_')
        .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
        .join('');

      return `import { ${originalClassName} as ${prefixedClassName} } from '${a.importPath}';`;
    })
    .join('\n');

  // Generate class name for mappings
  const toClassName = (varName: string) =>
    varName
      .split('_')
      .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
      .join('');

  const jobMapping = jobAgents
    .map((a) => `  '${a.key}': ${toClassName(a.variableName)},`)
    .join('\n');
  const persistentMapping = persistentAgents
    .map((a) => `  '${a.key}': ${toClassName(a.variableName)},`)
    .join('\n');

  // Type for job processors: class constructors that accept ProcessorConfig
  // Type for persistent: class constructors (no config needed)
  const content = `// This file is auto-generated by scripts/generate-agent-registry.ts
import type { JobProcessor, ProcessorConfig } from './core/processor.js';
import type { PersistentAgent } from './core/persistent.js';

${imports}

// Job processors are class constructors that accept ProcessorConfig
export const jobProcessors: Record<string, new (config: ProcessorConfig) => JobProcessor<unknown>> = {
${jobMapping}
};

// Persistent agents are class constructors (no config in constructor)
export const processors: Record<string, new () => PersistentAgent> = {
${persistentMapping}
};
`;

  const outputPath = path.join(ROOT_DIR, 'packages/agent/src/registry.ts');

  // Ensure directory exists
  await fs.mkdir(path.dirname(outputPath), { recursive: true });

  await fs.writeFile(outputPath, content);
  console.info(`Generated Agent registry at ${outputPath}`);
}

generate().catch(console.error);
