
import type { AstroIntegration } from 'astro';
import fs from 'node:fs';
import path from 'node:path';
import { ModuleDiscovery } from '../modules/module-discovery';
import { defu } from 'defu';

const OUTPUT_FILE = path.resolve(process.cwd(), 'src/lib/email/email-theme-config.ts');

/**
 * Astro integration to aggregate email theme configurations from modules.
 * This ensures that themes defined in modules (e.g. colors) are available
 * to the React Email compiler at runtime.
 */
export default (): AstroIntegration => {
    return {
        name: 'module-email-theme-integration',
        hooks: {
            'astro:config:setup': async ({ }) => {
                let aggregatedTheme = {};

                const modules = await ModuleDiscovery.loadModules();

                for (const module of modules) {
                    if (module.config && module.config.theme) {
                        // Merge current module theme onto the aggregated theme.
                        // defu(source, defaults) -> source wins.
                        // So we pass module.config.theme as source to override previous defaults.
                        aggregatedTheme = defu(module.config.theme, aggregatedTheme);
                        console.log(`[email-theme] Loaded theme from ${module.name}`);
                    }
                }

                // Generate the output file
                const fileContent = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * This file is generated by module-email-theme-integration.ts
 * It aggregates theme configurations from all modules for use in React Email.
 */
export const emailTheme = ${JSON.stringify(aggregatedTheme, null, 4)};

export default emailTheme;
`;

                // Ensure directory exists
                const outputDir = path.dirname(OUTPUT_FILE);
                if (!fs.existsSync(outputDir)) {
                    fs.mkdirSync(outputDir, { recursive: true });
                }

                fs.writeFileSync(OUTPUT_FILE, fileContent);
                console.log(`[email-theme] Generated email theme config at ${OUTPUT_FILE}`);
            },
        },
    };
};
