import { Project, SourceFile } from 'ts-morph';
import { UiBaseBuilder } from './ui-base-builder.js';
import { type FileDefinition, type ModuleConfig } from '../../types.js';
import { Reconciler } from '../../reconciler.js';
import { toPascalCase } from '../../../utils/string.js';

export class GuardBuilder extends UiBaseBuilder {
  constructor(
    protected moduleName: string,
    protected config: ModuleConfig,
  ) {
    super(moduleName, config);
  }

  async build(project: Project, sourceFile: SourceFile | undefined): Promise<void> {
    this.loadUiConfig();

    // 1. Generate Generic RoleGuard
    this.generateGenericGuard(project);

    // 2. Generate Specific Guards from Roles found in API
    // We look for 'roles' property in routes
    const routes = this.resolveRoutes();
    const roles = new Set<string>();

    if (routes) {
      routes.forEach((r) => {
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const route = r as any;
        if (route.roles && Array.isArray(route.roles)) {
          route.roles.forEach((role: string) => roles.add(role));
        }
      });
    }

    // Always add default roles if none found?
    // roles.add('ADMIN'); // Maybe?

    for (const role of roles) {
      this.generateSpecificGuard(project, role);
    }
  }

  private generateGenericGuard(project: Project) {
    const file = project.createSourceFile('src/components/guards/RoleGuard.tsx', '', {
      overwrite: true,
    });

    const definition: FileDefinition = {
      header: this.getHeader(),
      imports: [
        {
          moduleSpecifier: 'react',
          namedImports: ['ReactNode'],
        },
        // Assume useSession or similar exists in core or generated
        // For now, assume a placeholder useAuth hook
        {
          moduleSpecifier: '@/hooks/use-auth', // This needs to exist or be generated
          namedImports: ['useAuth'],
        },
      ],
      variables: [
        {
          name: 'RoleGuard',
          isExported: true,
          declarationKind: 'const',
          initializer: `({ children, roles, fallback }: { children: ReactNode, roles: string[], fallback?: ReactNode }) => {
    const { user, isLoading } = useAuth();
    
    if (isLoading) return null; // or spinner
    
    if (!user || !roles.some(role => user.roles.includes(role))) {
        return fallback || null;
    }

    return <>{children}</>;
}`,
        },
      ],
    };
    Reconciler.reconcile(file, definition);
  }

  private generateSpecificGuard(project: Project, role: string) {
    const componentName = `${toPascalCase(role)}Guard`;
    const file = project.createSourceFile(`src/components/guards/${componentName}.tsx`, '', {
      overwrite: true,
    });

    const definition: FileDefinition = {
      header: this.getHeader(),
      imports: [
        {
          moduleSpecifier: 'react',
          namedImports: ['ReactNode'],
        },
        {
          moduleSpecifier: './RoleGuard',
          namedImports: ['RoleGuard'],
        },
      ],
      variables: [
        {
          name: componentName,
          isExported: true,
          declarationKind: 'const',
          initializer: `({ children, fallback }: { children: ReactNode, fallback?: ReactNode }) => {
    return <RoleGuard roles={['${role}']} fallback={fallback}>{children}</RoleGuard>;
}`,
        },
      ],
    };
    Reconciler.reconcile(file, definition);
  }

  private getHeader(): string {
    return '// GENERATED CODE - DO NOT MODIFY\n// This file was generated by the GuardBuilder.';
  }
}
