import { Project, SourceFile } from 'ts-morph';
import { UiBaseBuilder } from './ui-base-builder.js';
import { type FileDefinition, type ModuleConfig } from '../../types.js';
import { Reconciler } from '../../reconciler.js';

export class RegistryBuilder extends UiBaseBuilder {
  constructor(
    protected moduleName: string,
    protected config: ModuleConfig,
  ) {
    super(moduleName, config);
  }

  async build(project: Project, sourceFile: SourceFile | undefined): Promise<void> {
    this.loadUiConfig();

    if (!this.uiConfig.navigation) {
      // If no navigation config, maybe skip or generate default?
      return;
    }

    const file = project.createSourceFile('src/registry/navigation.tsx', '', { overwrite: true });

    const nav = this.uiConfig.navigation;
    const label = nav.label || this.moduleName;
    // Default icon or path?
    const path = `/${this.moduleName}`;

    const definition: FileDefinition = {
      header: this.getHeader(),
      imports: [
        // import icon if needed, or types
      ],
      variables: [
        {
          name: 'navigation',
          isExported: true,
          declarationKind: 'const',
          initializer: `
{
    label: '${label}',
    path: '${path}',
    icon: '${nav.icon || 'Box'}',
    parent: ${nav.parent ? `'${nav.parent}'` : 'undefined'}
}`,
        },
      ],
    };
    Reconciler.reconcile(file, definition);
  }

  private getHeader(): string {
    return '// GENERATED CODE - DO NOT MODIFY\n// This file was generated by the RegistryBuilder.';
  }
}
