import { Project, SourceFile } from 'ts-morph';
import { UiBaseBuilder } from './ui-base-builder.js';
import { type FileDefinition, type ModuleConfig } from '../../types.js';
import { Reconciler } from '../../reconciler.js';

export class ShellBuilder extends UiBaseBuilder {
  constructor(
    protected moduleName: string,
    protected config: ModuleConfig,
  ) {
    super(moduleName, config);
  }

  async build(project: Project, sourceFile: SourceFile | undefined): Promise<void> {
    this.loadUiConfig();

    const file = project.createSourceFile('src/components/layout/ModuleShell.tsx', '', {
      overwrite: true,
    });

    const definition: FileDefinition = {
      header: this.getHeader(),
      imports: [
        {
          moduleSpecifier: 'react',
          namedImports: ['ReactNode'],
        },
        {
          moduleSpecifier: '@/components/providers/AuthProvider',
          namedImports: ['AuthProvider'],
        },
        // Assume generic core layout if valid, or just simple div
        // {
        //      moduleSpecifier: '@/components/shell/AppLayout',
        //      namedImports: ['AppLayout'],
        // }
      ],
      variables: [
        {
          name: 'ModuleShell',
          isExported: true,
          declarationKind: 'const',
          initializer: `({ children }: { children: ReactNode }) => {
    return (
        <AuthProvider>
            <div className="min-h-screen bg-gray-50">
                 {/* Standard Module Layout logic could go here */}
                {children}
            </div>
        </AuthProvider>
    );
}`,
        },
      ],
    };
    Reconciler.reconcile(file, definition);
  }

  private getHeader(): string {
    return '// GENERATED CODE - DO NOT MODIFY\n// This file was generated by the ShellBuilder.';
  }
}
