import { Project, SourceFile } from 'ts-morph';
import { UiBaseBuilder } from './ui-base-builder.js';
import { type FileDefinition, type ModelDef, type ModuleConfig } from '../../types.js';
import { Reconciler } from '../../reconciler.js';
import { toKebabCase, toPascalCase } from '../../../utils/string.js';

export class TableBuilder extends UiBaseBuilder {
  constructor(
    protected moduleName: string,
    protected config: ModuleConfig,
  ) {
    super(moduleName, config);
  }

  async build(project: Project, sourceFile: SourceFile | undefined): Promise<void> {
    this.loadUiConfig();
    const models = this.resolveModels();
    if (!models || models.length === 0) return;

    for (const model of models) {
      if (!model.api) continue;

      const componentName = `${toPascalCase(model.name)}Table`;
      const fileName = `src/components/${componentName}.tsx`;

      const file = project.createSourceFile(fileName, '', { overwrite: true });

      const definition: FileDefinition = {
        header: this.getHeader(),
        imports: [
          {
            moduleSpecifier: 'react',
            namedImports: ['useState'],
          },
          {
            moduleSpecifier: `@/hooks/use-${toKebabCase(model.name)}`,
            namedImports: [
              `use${toPascalCase(model.name)}Query`,
              `useDelete${toPascalCase(model.name)}`,
            ],
          },
          // Add UI components imports here if needed, e.g. from @/components/ui/table
        ],
        variables: [
          {
            name: componentName,
            isExported: true,
            declarationKind: 'const',
            initializer: this.generateComponent(model),
          },
        ],
      };

      Reconciler.reconcile(file, definition);
    }
  }

  private generateComponent(model: ModelDef): string {
    const modelName = toPascalCase(model.name);
    const hookName = `use${modelName}Query`;
    const deleteHookName = `useDelete${modelName}`;

    // Fields for columns
    const columns = Object.entries(model.fields)
      .filter(([name, f]) => !f.private && f.type !== 'Json' && !f.isRelation) // Simple columns for now
      .map(([name]) => name);

    // JSX Construction
    // We use string-based JSX construction via primitives if complex, or simple string if easier.
    // Using 'tsx' factory would be ideal but it returns AST nodes. Reconciler expects string initializer for variables?
    // Wait, Reconciler 'initializer' expects a STRING.
    // So we can use `tsx` to generate AST then print it? Or just write code string.
    // Writing code string is easier for block components. `tsx` is for granular AST.

    return `() => {
    const { data, isLoading } = ${hookName}();
    const deleteMutation = ${deleteHookName}();

    if (isLoading) return <div>Loading...</div>;

    return (
        <div className="overflow-x-auto">
            <table className="min-w-full divide-y divide-gray-200">
                <thead className="bg-gray-50">
                    <tr>
                        ${columns.map((col) => `<th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">${col}</th>`).join('\n                        ')}
                        <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Actions</th>
                    </tr>
                </thead>
                <tbody className="bg-white divide-y divide-gray-200">
                    {data?.data?.map((item: any) => (
                        <tr key={item.id}>
                            ${columns.map((col) => `<td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{String(item.${col})}</td>`).join('\n                            ')}
                            <td className="px-6 py-4 whitespace-nowrap text-sm font-medium">
                                <button className="text-red-600 hover:text-red-900" onClick={() => deleteMutation.mutate(item.id)}>Delete</button>
                            </td>
                        </tr>
                    ))}
                </tbody>
            </table>
        </div>
    );
}`;
  }

  private getHeader(): string {
    return '// GENERATED CODE - DO NOT MODIFY\n// This file was generated by the TableBuilder.';
  }
}
