import { type FileDefinition, type FunctionConfig } from '../types';
import { Reconciler } from '../reconciler';
import { BaseBuilder } from './base-builder';
import { SourceFile } from 'ts-morph';

export class InitBuilder extends BaseBuilder {
  constructor(private type: 'server' | 'client') {
    super();
  }

  protected getSchema(node?: any): FileDefinition {
    if (this.type === 'server') {
      return this.getServerSchema(node);
    } else {
      return this.getClientSchema(node);
    }
  }

  private getServerSchema(node?: any): FileDefinition {
    const initFunc: FunctionConfig = {
      name: 'init',
      isExported: true,
      isAsync: true,
      overwriteBody: true,
      parameters: [],
      statements: [
        `// 1. Auto-discover and Register Roles from src/roles/`,
        `const roleModules = import.meta.glob("./roles/*.ts", { eager: true });`,
        `for (const path in roleModules) {`,
        `    const mod = roleModules[path] as any;`,
        `    const roleName = path.split("/").pop()?.replace(".ts", "");`,
        `    if (!roleName) continue;`,
        `    `,
        `    // Find the first exported class that looks like a RolePolicy (has check method)`,
        `    for (const key in mod) {`,
        `        const Exported = mod[key];`,
        `        if (typeof Exported === "function" && Exported.prototype && Exported.prototype.check) {`,
        `            roleRegistry.register(roleName, new Exported());`,
        `            break;`,
        `        }`,
        `    }`,
        `}`,
        ``,
        `// 2. Auto-load all Hook definitions from src/hooks/`,
        `const hookModules = import.meta.glob("./hooks/*.ts", { eager: true });`,
        `for (const path in hookModules) {`,
        `    const mod = hookModules[path] as any;`,
        `    if (typeof mod.init === "function") {`,
        `        await mod.init();`,
        `    }`,
        `}`,
      ],
    };

    return {
      header: `// GENERATED CODE - DO NOT MODIFY BY HAND\n// This file is automatically generated by the ArcNexus Generator.\n// Any manual changes will be overwritten.`,
      imports: [
        { moduleSpecifier: '@/lib/registries/role-registry', namedImports: ['roleRegistry'] },
      ],
      functions: [initFunc],
    };
  }

  private getClientSchema(node?: any): FileDefinition {
    const initFunc: FunctionConfig = {
      name: 'init',
      isExported: true,
      isAsync: true,
      overwriteBody: true,
      parameters: [],
      statements: [`console.log("[Client] Initializing module...");`],
    };

    return {
      header: `// GENERATED CODE - DO NOT MODIFY BY HAND\n// This file is automatically generated by the ArcNexus Generator.\n// Any manual changes will be overwritten.`,
      functions: [initFunc],
    };
  }
}
